### PR TITLE
Add WSL guidance to start guide

### LINKED ISSUE #16: [missing guide info] WSL+ubuntu issues when making esp-open-sdk
Using WSL+ubuntu, I was stuck making esp-open-sdk due to a bash version mismatch, failure to change permissions, then due to windows being case insensitive.

I was able to make esp-open-sdk once I followed the directions [here](https://github.com/pfalcon/esp-open-sdk/issues/365) and [here](https://stackoverflow.com/a/50856772/1092820), set windows to be case sensitive as [here](https://crosstool-ng.github.io/docs/os-setup/), and restarted my system.

### PR DESCRIPTION
**Pull request by Ruzihm**
Fixes #16

### CODE REVIEW

**Comment by AEFeinstein** [comment]
Hm, did you check out those files somewhere on your Windows hard drive (/mnt/c/... in WSL) or on WSL's disk?

**Comment by Ruzihm** [comment]
oh jeeze yes. should i go fix the line endings?

**Comment by AEFeinstein** [comment]
The bash thing was still useful, but the file permissions definitely felt odd. Windows and Linux still aren't quite best friends, but you can access your WSL drive from Windows explorer.exe at `\\wsl$\Ubuntu`

**Comment by Ruzihm** [comment]
Oh, I see what you're getting at. I'll re-open then. 

Basically, because I cloned into  `/mnt/c/...`, crosstool-NG threw a fit about directory permissions. Should I remove that part and instead add a bit about not cloning into a windows directory e.g. `/mnt/c/...`?

**Comment by AEFeinstein** [comment]
That would be a wise bit in the guide, yes.

**Comment by Ruzihm** [comment]
Actually, with cloning into a non-windows dir, the case insensitivity fix may not be necessary. Let me close this again and update with my findings.

**Pull request merged**
