### PR TITLE
added emu stub for os_printf

### PR DESCRIPTION
**Pull request by bbkiwi**
Also quick fix for led scale 0 to 255 to 15 to 255
(will improve later)

NOTE it would be nice to astyle swadgemu.c but lots will change

### CODE REVIEW

**Comment by AEFeinstein** [comment]
Ah, I see we missed `os_printf()` because I disabled them all in order to get SwadgePass to boot quicker. Looks like `os_zalloc()` is missing too, but I can handle that. I'll also add a little `bool` to have `system_set_os_print()` control `os_printf()`. Nice catch again!

**Comment by AEFeinstein** [comment]
Also, @cnlohr , it would be nice to use `astyle`. I'll do that before merging `emu` to `master`

**Comment by cnlohr** [comment]
Understood.  I noticed there was a bit of a disagreement.

**Comment by AEFeinstein** [comment]
What disagreement?

**Comment by cnlohr** [comment]
The clash of my fabulous coding style.

**Pull request merged**
